# -*- coding: utf-8 -*-
"""Bandname_ generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZbeW5q48V11kHimdYHfJWd-Qsotti9c2
"""

print("Welcome to the Band Name Generator. ")
a=input("What's name of the city you grew up in?\n")
b=input("What's your pet's name?\n")
print("Your band name could be " + a +" "+  b)