# -*- coding: utf-8 -*-
"""love_calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vy8ShsgA0Ix6_dZiny9YMqrVy0jE-t3X
"""

print("Welcome to the Love Calculator!")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")


sum=(name1+name2).upper()

t=sum.count("T")
r=sum.count("R")
u=sum.count("U")
e=sum.count("E")
true=t+r+u+e

l=sum.count("L")
o=sum.count("O")
v=sum.count("V")
e=sum.count("E")
love=l+o+v+e

score=str(true)+str(love)
n=int(score)


if n <= 10 or n >= 90:
    print(f"Your score is {n}, you go together like coke and mentos.")

elif n >= 40 and n <= 50:
    print(f"Your score is {n}, you are alright together.")

else:
    print(f"Your score is {n}.")