# -*- coding: utf-8 -*-
"""Pizza _calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnCqqM4GWtqrpOutT6VGVsOOzQiNvlTb
"""

print("Welcome to Python Pizza Deliveries!")
size = input("What size pizza do you want? S, M, or L ")
add_pepperoni = input("Do you want pepperoni? Y or N ")
extra_cheese = input("Do you want extra cheese? Y or N ")

bill = 0

if size == "S":
    bill = bill + 15
    
    if add_pepperoni == "Y":
        bill = bill + 2
    
    else:
        bill = bill

    if extra_cheese == "Y":
        bill = bill + 1
    print(f"Your final bill is: ${bill}.") 

elif size == "M":
    bill = bill + 20
    
    if add_pepperoni == "Y":
        bill = bill + 3
    
    else:
        bill = bill

    if extra_cheese == "Y":
        bill = bill + 1
    print(f"Your final bill is: ${bill}.")      

elif size == "L":
    bill = bill + 25
    
    if add_pepperoni == "Y":
        bill = bill + 3
    
    else:
        bill = bill

    if extra_cheese == "Y":
        bill = bill + 1
    print(f"Your final bill is: ${bill}.") 





else:
    print("Please input S, M, L letters")