# -*- coding: utf-8 -*-
"""Tip_calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UxyJTaevsHUfSJbcwYewfTB1VhedYoQ6
"""

print("Welcome to the tip calculator")
a=float(input("What was the total bill?\n"))
b=int(input("What percentage tip would you like to give? 10, 12, or 15,\n"))
c=int(input("How many people to spilt the bill?\n"))

percent=float(1+(b/100))
total_bill=a*percent

spilt=round(total_bill/c ,2)
final_amount="{:.2f}".format(spilt)
print(f"Each person should pay {final_amount}")